server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /shop
logging:
  level:
    cn.edu.zzuli: trace
  path: /code/log/
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm} === [%thread] === %-5level === %logger{50} === %msg%n'
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
# 注意了这里的druid不是和上面的这些anemia一起的 name是在duriddatasource的里面的
# DruidDataSourceWrapper  durid是在wapper的里面的
    druid:
      query-timeout: 2400
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500