server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /shop
logging:
  level:
    cn.edu.zzuli: trace
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm} === [%thread] === %-5level === %logger{50} === %msg%n'
spring:
  thymeleaf:
    cache: false # ba cache 设置为false 是热部署静态文件的
    prefix: classpath:/templates
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource